# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Pull data
      run: |
        git clone https://github.com/CSSEGISandData/COVID-19.git ./data/raw/COVID-19-master
    
    - name: Execute the notebook and generate HTML
      run: |
        jupyter nbconvert --execute ./notebooks/co-vidis.ipynb
        jupyter nbconvert ./notebooks/co-vidis.ipynb --output-dir=./reports --TagRemovePreprocessor.remove_cell_tags='{"remove_cell"}' --TagRemovePreprocessor.remove_input_tags='{"remove_input"}'
  
    - name: Build for publication
      run: |
        mv reports/co-vidis.html reports/index.html

    - name: Deploy to netlify
      uses: netlify/actions/cli@master
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      with:
        args: deploy --prod --dir=reports
        secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
