# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 5,11,17 * * *'

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Conda and Install Dependencies
      uses: s-weigand/setup-conda@v1
      run: |
        conda --version
        which Python

    - name: Install Conda Environment
      run: |
        conda env create -f environment.yml
        conda activate co-vidis

    - name: Pull data
      run: |
        git clone https://github.com/CSSEGISandData/COVID-19.git ./data/raw/COVID-19-master
    
    - name: Execute the notebook
      run: |
        jupyter nbconvert ./notebooks/co-vidis.ipynb --execute --to notebook --output-dir=./reports
  
    - name: Build for publication
      run: |
        jupyter nbconvert ./reports/co-vidis.ipynb --output-dir=./reports --TagRemovePreprocessor.remove_cell_tags='{"remove_cell"}' --TagRemovePreprocessor.remove_input_tags='{"remove_input"}'
        rm ./reports/co-vidis.ipynb
        mv ./reports/co-vidis.html ./reports/index.html

    - name: Deploy to netlify
      uses: netlify/actions/cli@master
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      with:
        args: deploy --prod --dir=reports
        secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
